package xyz.javecs.tools.expr

fun Double.sin(): Double = Math.sin(this)
fun Double.cos(): Double = Math.cos(this)
fun Double.tan(): Double = Math.tan(this)
fun Double.asin(): Double = Math.asin(this)
fun Double.acos(): Double = Math.acos(this)
fun Double.atan(): Double = Math.atan(this)
fun Double.exp(): Double = Math.exp(this)
fun Double.log(): Double = Math.log(this)
fun Double.log10(): Double = Math.log10(this)
fun Double.sqrt(): Double = Math.sqrt(this)
fun Double.cbrt(): Double = Math.cbrt(this)
fun Double.ceil(): Double = Math.ceil(this)
fun Double.floor(): Double = Math.floor(this)
fun Double.rint(): Double = Math.rint(this)
fun Double.abs(): Double = Math.abs(this)
fun Double.ulp(): Double = Math.ulp(this)
fun Double.signum(): Double = Math.signum(this)
fun Double.sinh(): Double = Math.sinh(this)
fun Double.cosh(): Double = Math.cosh(this)
fun Double.tanh(): Double = Math.tanh(this)
fun Double.expm1(): Double = Math.expm1(this)
fun Double.log1p(): Double = Math.log1p(this)

fun builtIn() = HashMap<String, (Double) -> Double>().apply {
    put("sin", { x -> x.sin() })
    put("cos", { x -> x.cos() })
    put("tan", { x -> x.tan() })
    put("asin", { x -> x.asin() })
    put("acos", { x -> x.acos() })
    put("atan", { x -> x.atan() })
    put("exp", { x -> x.exp() })
    put("log", { x -> x.log() })
    put("log10", { x -> x.log10() })
    put("sqrt", { x -> x.sqrt() })
    put("cbrt", { x -> x.cbrt() })
    put("ceil", { x -> x.ceil() })
    put("floor", { x -> x.floor() })
    put("rint", { x -> x.rint() })
    put("abs", { x -> x.abs() })
    put("ulp", { x -> x.ulp() })
    put("signum", { x -> x.signum() })
    put("sinh", { x -> x.sinh() })
    put("cosh", { x -> x.cosh() })
    put("tanh", { x -> x.tanh() })
    put("expm1", { x -> x.expm1() })
    put("log1p", { x -> x.log1p() })
}
